/**
 * Vault API
 * Vault API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
    /**
     *
     * @type {string}
     * @memberof CreateUserDto
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof CreateUserDto
     */
    firstName: string;
    /**
     *
     * @type {string}
     * @memberof CreateUserDto
     */
    lastName: string;
    /**
     *
     * @type {string}
     * @memberof CreateUserDto
     */
    password: string;
}
