/**
 * Vault API
 * Vault API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateUserDTO
 */
export interface CreateUserDTO {
    /**
     *
     * @type {string}
     * @memberof CreateUserDTO
     */
    email: string;
    /**
     *
     * @type {string}
     * @memberof CreateUserDTO
     */
    password: string;
}
