/* tslint:disable */
/* eslint-disable */
/**
 * Vault API
 * Vault API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DailyDataPointsDTO
 */
export interface DailyDataPointsDTO {
    /**
     * 
     * @type {string}
     * @memberof DailyDataPointsDTO
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof DailyDataPointsDTO
     */
    value: number;
}
