/**
 * Vault API
 * Vault API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Account } from './account';
import { User } from './user';
/**
 *
 * @export
 * @interface Item
 */
export interface Item {
  /**
   *
   * @type {number}
   * @memberof Item
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Item
   */
  itemId: string;
  /**
   *
   * @type {string}
   * @memberof Item
   */
  updateType: string;
  /**
   *
   * @type {string}
   * @memberof Item
   */
  accessToken: string;
  /**
   *
   * @type {string}
   * @memberof Item
   */
  transactionSyncCursor?: string;
  /**
   *
   * @type {User}
   * @memberof Item
   */
  user: User;
  /**
   *
   * @type {Array<Account>}
   * @memberof Item
   */
  accounts: Array<Account>;
}
