/**
 * Vault API
 * Vault API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface LinkTokenDTO
 */
export interface LinkTokenDTO {
  /**
   *
   * @type {string}
   * @memberof LinkTokenDTO
   */
  token: string;
}
