/* tslint:disable */
/* eslint-disable */
/**
 * Vault API
 * Vault API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PlaidItem } from './plaid-item';
import { PlaidTransaction } from './plaid-transaction';
/**
 * 
 * @export
 * @interface PlaidAccount
 */
export interface PlaidAccount {
    /**
     * 
     * @type {number}
     * @memberof PlaidAccount
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccount
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccount
     */
    mask: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccount
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccount
     */
    officialName: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccount
     */
    subtype: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccount
     */
    type: string;
    /**
     * 
     * @type {PlaidItem}
     * @memberof PlaidAccount
     */
    plaidItem: PlaidItem;
    /**
     * 
     * @type {Array<PlaidTransaction>}
     * @memberof PlaidAccount
     */
    plaidTransactions: Array<PlaidTransaction>;
}
