/**
 * Vault API
 * Vault API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Rule
 */
export interface Rule {
    /**
     *
     * @type {string}
     * @memberof Rule
     */
    field: RuleFieldEnum;
    /**
     *
     * @type {string}
     * @memberof Rule
     */
    operation: RuleOperationEnum;
    /**
     *
     * @type {number}
     * @memberof Rule
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof Rule
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof Rule
     */
    criteria: string;
    /**
     *
     * @type {boolean}
     * @memberof Rule
     */
    isEnabled: boolean;
}
/**
    * @export
    * @enum {string}
    */
export declare enum RuleFieldEnum {
    Name = "name",
    TransactionId = "transactionId",
    PaymentChannel = "paymentChannel"
}
/**
    * @export
    * @enum {string}
    */
export declare enum RuleOperationEnum {
    Contains = "contains",
    Equals = "equals"
}
