/* tslint:disable */
/* eslint-disable */
/**
 * Vault API
 * Vault API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateRuleDTO
 */
export interface UpdateRuleDTO {
    /**
     * 
     * @type {string}
     * @memberof UpdateRuleDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRuleDTO
     */
    criteria?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateRuleDTO
     */
    isEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateRuleDTO
     */
    field?: UpdateRuleDTOFieldEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateRuleDTO
     */
    operation?: UpdateRuleDTOOperationEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum UpdateRuleDTOFieldEnum {
    Name = 'name',
    TransactionId = 'transactionId',
    PaymentChannel = 'paymentChannel'
}
/**
    * @export
    * @enum {string}
    */
export enum UpdateRuleDTOOperationEnum {
    Contains = 'contains',
    Equals = 'equals'
}

