FROM node:18.7-alpine AS NEST_BUILDER

# create the directory inside the container
WORKDIR /app

# Copy over server folder
COPY ./server ./

# run yarn install in our local machine
RUN yarn install --frozen-lockfile

# build everything
RUN yarn test 

# build everything
RUN yarn build

# remove development dependencies
RUN yarn install --production --ignore-scripts

#Remove src, test, and config folders if they exist
RUN rm -rf src test config