name: CI
on:
  push:
    - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: true

jobs:
  test:
    name: Lint & Test Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Client Dependencies
        run: cd client && yarn

      - name: Lint Client
        run: cd client && yarn lint

      - name: Build Client
        run: cd client && yarn build
